
        
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          site-directory: ./out # Replace with the path to your built Next.js files
          server: ${{ secrets.ftp_SERVER }
          username: ${{ secrets.ftp_USERNAME }}
          password: ${{ secrets.ftp_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
